# Generated by Django 2.2.9 on 2020-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20200303_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(max_length=500),
        ),
    ]
