# Generated by Django 2.2.9 on 2020-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teablends', '0004_remove_teablend_feelings'),
        ('feelings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='teablends',
            field=models.ManyToManyField(related_name='feelings', to='teablends.Teablend'),
        ),
    ]
