# Generated by Django 2.2.9 on 2020-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0007_auto_20200303_1043'),
        ('feelings', '0002_feeling_teablends'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='loveletters',
            field=models.ManyToManyField(blank=True, related_name='_feeling_loveletters_+', to='loveletters.LoveLetter'),
        ),
    ]
