# Generated by Django 2.2.9 on 2020-03-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0003_feeling_loveletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='loveletters',
            field=models.ManyToManyField(blank=True, related_name='feelings', to='loveletters.LoveLetter'),
        ),
    ]
