# Generated by Django 2.2.9 on 2020-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0004_auto_20200303_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='loveletters',
            field=models.ManyToManyField(blank=True, related_name='_feeling_loveletters_+', to='loveletters.LoveLetter'),
        ),
    ]
