# Generated by Django 2.2.9 on 2020-02-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('penpal_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('love_letter', models.CharField(max_length=800)),
            ],
        ),
    ]
