# Generated by Django 2.2.9 on 2020-02-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loveletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='feelings',
            field=models.ManyToManyField(blank=True, related_name='loveletters', to='feelings.Feeling'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('loveletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loveletters.LoveLetter')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
