# Generated by Django 2.2.9 on 2020-02-27 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='loveletter',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
