# Generated by Django 2.2.9 on 2020-03-02 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0005_auto_20200228_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loveletter',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='loveletter',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='love_letter', to=settings.AUTH_USER_MODEL),
        ),
    ]
