# Generated by Django 2.2.9 on 2020-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0006_auto_20200302_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loveletter',
            name='feelings',
            field=models.ManyToManyField(blank=True, related_name='_loveletter_feelings_+', to='feelings.Feeling'),
        ),
    ]
