# Generated by Django 2.2.9 on 2020-03-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0007_auto_20200303_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loveletter',
            name='feelings',
        ),
    ]
