# Generated by Django 2.2.9 on 2020-03-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0009_auto_20200303_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loveletter',
            name='feelings',
        ),
    ]
