# Generated by Django 2.2.9 on 2020-03-03 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loveletters', '0011_loveletter_feelings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loveletter',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='loveletter',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loveletters_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
