# Generated by Django 2.2.9 on 2020-02-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teablend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb', models.CharField(max_length=30)),
                ('herb_property', models.CharField(max_length=300)),
            ],
        ),
    ]
