# Generated by Django 2.2.9 on 2020-02-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teablends', '0002_teablend_feelings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teablend',
            old_name='herb',
            new_name='herb_name',
        ),
    ]
