# Generated by Django 2.2.9 on 2020-02-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teablends', '0003_auto_20200227_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teablend',
            name='feelings',
        ),
    ]
